### PR TITLE
Making building possible again

### PR DESCRIPTION
**Pull request by vitor251093**
I'm using macOS Sierra, and building the original project had lots of complications, like:

- The pod used to download the Google API wasn't working, and had to be replaced. That doesn't required a big code change though.
- Cocoapods was updated, and now seems to require a target in the Podfile.
- MASPreferences had to be updated in the Podfile in order to compile.

I've also made some other changes in the project that were suggested by Xcode. 

I'm not sure if your still an active user, since you don't have any activity for almost a year, so I've also update the README file to do not mention the version 3 of the app when I forked it; hope you don't mind since you can add it back :P 

I've also fixed the README file formatting to show up properly. I just couldn't create a client ID and secret key to make the app work properly, but I'm not sure if the problem is on my side or if the updated GTMOAuth2 requires something else.

### CODE REVIEW

**Comment by jashephe** [comment]
Hi @vitor251093 -- it's nice to see your interest! I've actually largely migrated away from OS X at this point, which is why this project has largely fallen by the wayside. Apologies for not updating the README to reflect the lack of maintenance.

If you want to merge this, I would like to take some time for review, since it does contain a decent number of changes, and I'd be inclined to wait until High Sierra drops. However, again, since I no longer actively maintain this project, if you would like to host development in your own fork, I would be happy to post a message in the README alerting users to the development freeze and pointing them your way.

If you are interested, there is a pretty substantial amount of work that went into the devel branch, and I regret that it never culminated in a release. Several requested features such as multiple account support and the corresponding OAuth infrastructure were developed, although there is still a great deal of work to be done. If you'd like to work on improving Gmail Notifier, there may be some code of value on devel (although note that since Swift has such rapid version changes, I'm sure that there are changes that need to be made to update the code to the latest language spec).

**Comment by vitor251093** [comment]
> Hi @vitor251093 -- it's nice to see your interest! I've actually largely migrated away from OS X at this point, which is why this project has largely fallen by the wayside. Apologies for not updating the README to reflect the lack of maintenance.

No worries ;)

> If you want to merge this, I would like to take some time for review, since it does contain a decent number of changes, and I'd be inclined to wait until High Sierra drops.

Surely. I wouldn't expect less :)

> However, again, since I no longer actively maintain this project, if you would like to host development in your own fork, I would be happy to post a message in the README alerting users to the development freeze and pointing them your way.

It's a possibility, but for the future. I can't say I will have time to dedicate myself to the project now, but I intend to do, since I would also like to use the and improve the app once I can make it work. I'm just having problems with the client ID and secret key (correcting what I said before, I **did** create them, but I always receive an Unauthorized error).

> If you are interested, there is a pretty substantial amount of work that went into the devel branch, and I regret that it never culminated in a release. Several requested features such as multiple account support and the corresponding OAuth infrastructure were developed, although there is still a great deal of work to be done. 

I will check it to get the completed the features ;)

> If you'd like to work on improving Gmail Notifier, there may be some code of value on devel (although note that since Swift has such rapid version changes, I'm sure that there are changes that need to be made to update the code to the latest language spec).

Considering you wrote your code 3 years ago, yup, Swift had lots of changes :P 

I had a project in my university job and we had to create a separated branch just for moving the code from Swift 2.3 to Swift 3 due to the lack of Swift 3 versions for the needed Pod dependencies, and using Swift 2.3 dependencies required many adjusts. We ended up waiting until these dependencies released their Swift 3 versions :P

I think I will just stick with the Objective-C version of the project and convert the new features from Swift to Objective-C.

**Comment by jashephe** [comment]
Okay, well, in that case, rather than merging this pull request, I will just update the README to reference your repository. If that's okay with you, I will close this pull request and update the README directly.

**Comment by vitor251093** [comment]
It's ok for me ;)

**Comment by jashephe** [comment]
I have updated the README as discussed. Good luck with any improvements!

**Pull request closed without merging**
